### ISSUE TITLE
ERROR:  message_filters/sync_policies/latest_time.h: No such file or directory

### ISSUE THREAD

**Issue by jprodriguezg** [Fixit-Davide/PX4-ROS2-Drone-Composable#1]
Hello there,

I am having the following error while compiling the package.

> #include "message_filters/sync_policies/latest_time.h"

After a fast check, I realized that ` latest_time.h` is not available in ROS Foxy (the ROS version I am currently using). I am wondering if you are considering to have a branch that can solve this issue in Foxy.

Thanks!

**Comment by Fixit-Davide** [comment]
I've made a new branch that doesn't use the Message Filters. Now it should work with ROS2 Foxy.  
I've changed the subscription topic to /vehicle_odometry that gives the same informations so there should be no changes in the behavior of the node.

**Comment by jprodriguezg** [comment]
Thank you @Fixit-Davide !
